apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
spec:
  loadBalancerIPs: true
  externalIPs: true
  interfaces:
    - enp0s3 # REEMPLAZA con el nombre de tu interfaz de red principal
  nodeSelector: {} # Puedes usar un selector para aplicar esta política a nodos específicos
  serviceSelector: {} # Puedes usar un selector para aplicar esta política a servicios específicos
